apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: debian-ssh-12-6-2024-11-11-0803
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: debian-ssh
  config:
    image: ghcr.io/labring-actions/devbox/debian-ssh-12.6:stable
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: debian-ssh 12.6
  version: "12.6"
  runtimeVersion: 2024-11-11-0803
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: debian-ssh
spec:
  title: "debian"
  kind: OS
  description: debian-ssh
